version: "3.8"
services:
  nx-example:
    build:
        context: .
        dockerfile: Dockerfile
        target: development
    container_name: nx-example
    tty: true
    stdin_open: true
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
        - .:/usr/src/app
